<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="172437" started-at="2019-11-27T11:48:09Z" finished-at="2019-11-27T11:51:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="172437" started-at="2019-11-27T11:48:09Z" finished-at="2019-11-27T11:51:02Z">
      <class name="shoppingCart.TestAddCartNumber">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="doBeforeClass" is-config="true" duration-ms="19455" started-at="2019-11-27T19:48:09Z" finished-at="2019-11-27T19:48:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="testLogin" duration-ms="34084" started-at="2019-11-27T19:48:29Z" description="登录" finished-at="2019-11-27T19:49:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="test_Open2()[pri:1, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_Open2" duration-ms="29759" started-at="2019-11-27T19:49:03Z" description="打开商品详情25" finished-at="2019-11-27T19:49:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Open2 -->
        <test-method status="PASS" signature="test_04_addGoodsNuByButton1()[pri:5, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_04_addGoodsNuByButton1" duration-ms="12785" started-at="2019-11-27T19:49:32Z" description="点击一次商品数量右侧的+号" depends-on-methods="shoppingCart.TestAddCartNumber.test_Open2" finished-at="2019-11-27T19:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_04_addGoodsNuByButton1 -->
        <test-method status="PASS" signature="test_05_addGoodsNuByButton2()[pri:10, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_05_addGoodsNuByButton2" duration-ms="24481" started-at="2019-11-27T19:49:45Z" description="点击多次商品数量右侧的+号" finished-at="2019-11-27T19:50:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_05_addGoodsNuByButton2 -->
        <test-method status="PASS" signature="test_06_addGoodsNuByButton2()[pri:15, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_06_addGoodsNuByButton2" duration-ms="24331" started-at="2019-11-27T19:50:10Z" description="点击商品数量左侧的-号" finished-at="2019-11-27T19:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_06_addGoodsNuByButton2 -->
        <test-method status="FAIL" signature="test_08_addGoodsNumFail01()[pri:20, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_08_addGoodsNumFail01" duration-ms="4580" started-at="2019-11-27T19:50:34Z" description="选择商品数量: -1 失败" finished-at="2019-11-27T19:50:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at shoppingCart.TestAddCartNumber.test_08_addGoodsNumFail01(TestAddCartNumber.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_08_addGoodsNumFail01 -->
        <test-method status="FAIL" signature="test_10_addGoodsNumFail02()[pri:25, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_10_addGoodsNumFail02" duration-ms="10645" started-at="2019-11-27T19:50:39Z" description="选择商品数量 0  失败" finished-at="2019-11-27T19:50:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at shoppingCart.TestAddCartNumber.test_10_addGoodsNumFail02(TestAddCartNumber.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_10_addGoodsNumFail02 -->
        <test-method status="PASS" signature="test_12_addGoodsNumFail03()[pri:30, instance:shoppingCart.TestAddCartNumber@2ff4f00f]" name="test_12_addGoodsNumFail03" duration-ms="12164" started-at="2019-11-27T19:50:49Z" description="选择商品数量  库存数+1 失败" finished-at="2019-11-27T19:51:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_12_addGoodsNumFail03 -->
      </class> <!-- shoppingCart.TestAddCartNumber -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
