<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GAD15EJN" name="shoppingCart.TestCart01" tests="9" failures="1" timestamp="6 Dec 2019 07:19:21 GMT" time="134.000" errors="0">
  <testcase name="testSkipToCart" time="4.092" classname="shoppingCart.TestCart01"/>
  <testcase name="testMoveCollectPartSelectGoods" time="7.318" classname="shoppingCart.TestCart01"/>
  <testcase name="testDeletePartSelectGoods" time="7.263" classname="shoppingCart.TestCart01"/>
  <testcase name="test_AddGood01" time="12.871" classname="shoppingCart.TestCart01"/>
  <testcase name="testMoveCollectItemButton" time="1.644" classname="shoppingCart.TestCart01"/>
  <testcase name="testPaytotalNoSelectGoods" time="7.832" classname="shoppingCart.TestCart01">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at shoppingCart.TestCart01.testPaytotalNoSelectGoods(TestCart01.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- testPaytotalNoSelectGoods -->
  <testcase name="test_CartContainsMyGoods" time="29.045" classname="shoppingCart.TestCart01"/>
  <testcase name="testDeleteItemButton" time="0.978" classname="shoppingCart.TestCart01"/>
  <testcase name="testLogin" time="62.957" classname="shoppingCart.TestCart01"/>
</testsuite> <!-- shoppingCart.TestCart01 -->
