<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GAD15EJN" name="wxp_ShoppingCart.TestAddCart" tests="16" failures="2" timestamp="8 Dec 2019 02:06:24 GMT" time="314.770" errors="0">
  <testcase name="test_12_addGoodsNumFail03" time="11.252" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_Open1" time="20.840" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_05_addGoodsNuByButton3" time="27.122" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_Open2" time="16.899" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.494" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.505" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_06_addGoodsNuByButton2" time="26.934" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.462" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.442" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_04_addGoodsNuByButton1" time="10.832" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_10_addGoodsNumFail02" time="13.571" classname="wxp_ShoppingCart.TestAddCart">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at wxp_ShoppingCart.TestAddCart.test_10_addGoodsNumFail02(TestAddCart.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_10_addGoodsNumFail02 -->
  <testcase name="test_03_AddCartDifferentProperty" time="20.518" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.561" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="testLogin" time="37.144" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_03_AddCartDifferentProperty" time="20.599" classname="wxp_ShoppingCart.TestAddCart"/>
  <testcase name="test_08_addGoodsNumFail01" time="6.595" classname="wxp_ShoppingCart.TestAddCart">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at wxp_ShoppingCart.TestAddCart.test_08_addGoodsNumFail01(TestAddCart.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_08_addGoodsNumFail01 -->
</testsuite> <!-- wxp_ShoppingCart.TestAddCart -->
